version: 2.1

orbs:
  aws-s3: circleci/aws-s3@1.0.11
jobs:
  build:
    docker:
      - image: circleci/node:16.13.1

    working_directory: ~/repo

    steps:
      - checkout

      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "package.json" }}
            # fallback to using the latest cache if no exact match is found
            - v1-dependencies-
      - run: yarn install

      - save_cache:
          paths:
            - node_modules
            - ~/.npm
            - ~/.cache
          key: v1-dependencies-{{ checksum "package.json" }}

      - run: yarn test

      - run: yarn build

      - run: curl "https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip" -o "awscliv2.zip"

      - run: sudo unzip awscliv2.zip

      - run: sudo ./aws/install

      - aws-s3/sync:
          from: build
          to: "s3://learnci/"
          arguments: |
            --acl public-read \
            --cache-control "max-age=86400"
          overwrite: true
